/*global define: false */
/**
 * Data for the "Cultural Roots" advantage described in Chapter 7 of Gaia:
 * Beyond the Dreams.
 * @module cultural_roots
 */
define({
    'Abel (Middle Class / Lower Class)': {Athleticism: 15, Ride: 10, Swim: 10, Notice: 15, 'Slight of Hand': 10, Persuasion: 10, History: {local: 10}},
    'Abel (Bourgeois)': {Ride: 10, Swim: 10, Persuasion: 15, Style: 10, History: {local: 10}, Appraisal: 15, Dance: 10},
    'Abel (Nobility / High Nobility)': {Ride: 10, Style: 10, Leadership: 20, Persuasion: 10, History: {local: 10}, Dance: 10, choices: [{Art: 10, Music: 10}]},
    'Alberia (Middle Class / Lower Class)': {Athleticism: 10, Climb: 10, Notice: 10, Track: 10, Animals: 10, 'Herbal Lore': 10, Stealth: 10, 'Trap Lore': 10},
    'Alberia (Nobility)': {Athleticism: 10, Climb: 10, Notice: 10, Music: 15, Leadership: 15, Persuasion: 10, History: {local: 10}},
    'Argos (Middle Class / Low Class)': {Athleticism: 10, Ride: 10, Climb: 10, Notice: 10, Track: 5, History: {local: 10}, 'Resist Pain': 10, Occult: {religion: 15}},
    'Argos (Nobility)': {Athleticism: 10, Ride: 10, Leadership: 20, Notice: 10, Composure: 5, History: {local: 15}, Occult: {religion: 10}},
    'Arlan (Middle Class / Lower Class)': {Ride: 5, Swim: 10, Persuasion: 20, History: {local: 10}, Appraisal: 20, Navigation: 15},
    'Arlan (Bourgeois / High Bourgeoisie)': {Ride: 10, Swim: 10, Persuasion: 20, Style: 5, History: {local: 10}, Appraisal: 20, Navigation: 5},
    'Baho (The Scholar Caste)': {Swim: 10, Persuasion: 10, Notice: 10, Animals: 5, Science: 15, History: 5, Memorize: 10, Art: 15},
    'Baho (The Warrior Caste)': {Athleticism: 10, Swim: 10, Climb: 10, Intimidate: 15, Notice: 5, Composure: 10, 'Feats of Strength': 10, 'Resist Pain': 10},
    'Bellafonte (Middle Class / Lower Class)': {Athleticism: 10, Ride: 15, Swim: 5, Notice: 10, Composure: 10, 'Feats of Strength': 10, History: {local: 10}, Occult: {religion: 10}},
    'Bellafonte (Nobility / High Nobility)': {Athleticism: 10, Ride: 15, Leadership: 20, Notice: 5, Composure: 10, History: {local: 10}, Occult: {religion: 10}},
    'Dalaborn (Middle Class / Lower Class)': {Athleticism: 10, Ride: 10, Intimidate: 10, Notice: 10, Composure: 10, 'Feats of Strength': 10, History: {local: 10}, Forging: 10},
    'Dalaborn (Nobility / High Nobility)': {Athleticism: 10, Ride: 10, Intimidate: 10, Leadership: 20, Notice: 10, Composure: 10, History: {local: 10}},
    'Dwänholf (Middle Class / Poor Class)': {Swim: 10, Intimidate: 15, Persuasion: 5, Notice: 15, Navigation: 10, Hide: 10, Theft: 10, Stealth: 5},
    'Dwänholf (Wealthy Class)': {Swim: 10, Initimidate: 10, Persuasion: 20, Notice: 10, Leadership: 10, Theft: 5, Appraisal: 15},
    'Estigia (Middle Class / Lower Class)': {Athleticism: 10, Notice: 15, Tracking: 10, History: {local: 10}, Occult: {religion: 10}, Appraisal: 5, Art: 5, Forging: 15},
    'Estigia (Bourgeois Bureaucrat / Nobility)': {Ride: 10, Style: 15, Intimidate: 5, Persuasion: 10, Notice: 5, History: {local: 15}, Occult: {religion: 15}, Art: 5},
    'Gabriel (Middle Class / Indigent)': {Atheticism: 10, Acrobatics: 10, Ride: 10, Swim: 10, Persuasion: 10, Notice: 10, History: {local: 10}, 'Feats of Strength': 10},
    'Gabriel (Bourgeois)': {Ride: 10, Style: 10, Persuasion: 20, Appraisal: 10, History: 10, Dance: 15, choices: [{Art: 5, Music: 5}]},
    'Gabriel (Nobility / High Nobility)': {Ride: 10, Style: 20, Leadership: 10, Persuasion: 10, History: 10, Dance: 10, choices: [{Art: 5, Music: 5}]},
    'Galgados (Middle Class / Lower Class)': {Acrobatics: 5, Athleticism: 15, Climb: 10, Notice: 10, Track: 10, Animals: 10, 'Herbal Lore': 10, Stealth: 10},
    'Goldar (Exiled / Peasant)': {Athleticism: 15, Ride: 10, Swim: 10, Hide: 10, Notice: 10, Track: 15, Animals: 5, 'Herbal Lore': 5},
    'Goldar (Northerner)': {Athleticism: 10, Ride: 10, Swim: 10, Intimidate: 10, Notice: 10, Track: 10, Animals: 5, 'Feats of Strength': 15},
    'Goldar (Erling, Sklamo or Honorable Escaldo)': {Athleticism: 10, Ride: 10, Swim: 10, choices: [{Intimidate: 10, Music: 10}, {Track: 10, History: {local: 10}}], Notice: 10, Animals: 10, Leadership: 10},
    'Haufman (Northern / Northern Peasant)': {Athleticism: 10, Climb: 10, Intimidate: 10, Notice: 10, Track: 10, Composure: 10, 'Feats of Strength': 10, 'Resist Pain': 10},
    'Haufman (Saerinmir)': {Athleticism: 10, Climb: 10, Intimidate: 10, Notice: 10, Swim: 10, Composure: 10, Navigation: 10, 'Resist Pain': 10},
    'Haufman (Nobleman)': {Athleticism: 10, Intimidate: 10, Notice: 10, Leadership: 20, Composure: 10, History: {local: 10}, 'Resist Pain': 10},
    'Helenia (Middle Class / Lower Class)': {Athleticism: 10, Ride: 20, Climb: 10, Swim: 10, Notice: 10, Animals: 10, 'Herbal Lore': 10},
    'Helenia (Nomad)': {Athleticism: 10, Ride: 20, Climb: 10, Animals: 10, 'Herbal Lore': 20, Track: 10},
    'Helenia (Nobility)': {Athleticism: 10, Ride: 20, Climb: 10, Swim: 10, Notice: 10, Animals: 10, Leadership: 10},
    'Hendell (Peasant)': {Athleticism: 10, Ride: 10, History: {local: 10}, Notice: 10, Track: 10, Animals: 15, 'Herbal Lore': 15},
    'Hendell (Northerner)': {Athleticism: 10, Ride: 10, History: {local: 10}, Intimidate: 10, Notice: 10, Track: 10, Animals: 10, 'Feats of Strength': 10},
    'Hendell (Lochgjest)': {Athleticism: 10, Swim: 10, Notice: 10, Track: 10, 'Resist Pain': 10, Hide: 10, Stealth: 10, Memorize: 10},
    'Hendell (The First Caste)': {Athleticism: 10, Ride: 10, History: {local: 10}, Intimidate: 10, Notice: 10, Leadership: 10, Persuasion: 10, Appraisal: 10},
    'Ilmora (Middle Class / Lower Class)': {Leadership: 10, Persuasion: 10, Science: 10, 'Herbal Lore': 10, History: 10, Medicine: 10, Memorize: 10, Art: 10},
    'Ilmora (Nobility / High Nobility)': {Leadership: 10, Persuasion: 10, Science: 10, History: 10, Dance: 10, Style: 10, Memorize: 10, Art: 10},
    'Kanon (Middle Class / Lower Class)': {Athleticism: 10, Ride: 10, Swim: 15, Notice: 10, Animals: 10, 'Herbal Lore': 10, Navigation: 15},
    'Kanon (Nobility)': {Athleticism: 10, Ride: 10, Leadership: 10, Notice: 10, Persuasion: 10, History: {local: 10}, Navigation: 20},
    'Kashmir (All the inhabitants of The Savannah)': {Athleticism: 20, Swim: 5, Notice: 10, Track: 15, Animals: 10, 'Herbal Lore': 5, Hide: 5, Stealth: 10},
    'Kushistan (Middle Class / Low Class)': {Athleticism: 10, Ride: 10, Climb: 10, Notice: 10, Track: 15, Animals: 10, Occult: {religion: 5}, Stealth: 10},
    'Kushistan (Bourgeois / Nobility)': {Ride: 10, Leadership: 10, Persuasion: 15, Style: 10, History: {local: 10}, Occult: {religion: 10}, Appraisal: 15},
    'Lannet (Lower Class)': {Athleticism: 15, Swim: 10, Climb: 10, Notice: 10, Animals: 5, Herbalism: 10, Occult: {religion: 10}, 'Feats of Strength': 10},
    'Lannet (Bourgeois / Samurai (courtesan))': {Athleticism: 10, Swim: 10, Style: 20, Persuasion: 10, History: {local: 10}, Art: 10, Music: 10},
    'Lannet (Samurai (warrior))': {Athleticism: 10, Ride: 10, Swim: 10, Style: 10, Intimidate: 10, Notice: 10, History: {local: 10}, Composure: 10},
    'Lucrecio (Middle Class / Low Class)': {Athleticism: 10, Ride: 10, Notice: 10, Science: 10, History: 10, Memorize: 10, 'Herbal Lore': 10, Animals: 10},
    'Lucrecio (High Class / High Bourgeoisie)': {Athleticism: 10, Ride: 10, Persuasion: 10, Notice: 10, Science: 10, History: 10, Memorize: 10, choices: [{Art: 10, Music: 10}]},
    'Moth (Middle Class / Lower Class)': {Ride: 10, Climb: 10, Notice: 15, Track: 10, 'Herbal Lore': 15, Occult: {'local myths': 10}, Composure: 10},
    'Moth (Zigeuner)': {Ride: 10, Climb: 10, Notice: 10, Track: 10, 'Herbal Lore': 5, Animals: 5, Persuasion: 10, Appraisal: 10, Occult: {'local myths': 20}},
    'Moth (Nobility)': {Ride: 10, Notice: 10, 'Herbal Lore': 10, Occult: {'local myths': 15}, Composure: 10, Leadership: 15, Intimidate: 10},
    'Nanwe (All members of local tribes)': {Athleticism: 10, Climb: 10, Notice: 10, Track: 10, Animals: 10, 'Herbal Lore': 10, Hide: 10, Stealth: 10},
    'Nanwe (Citizen Middle Class / Bourgeois)': {Swim: 10, Climb: 5, Persuasion: 10, Notice: 15, Track: 15, Animals: 15, Hide: 5, Stealth: 5},
    'Phaion Eien Seimon (Middle Class / Lower Class)': {Athleticism: 10, Ride: 10, Swim: 10, Persuasion: 15, Notice: 10, History: {local: 10}, Navigation: 10, 'Feats of Strength': 5},
    'Phaion Eien Seimon (Bourgeois / Nobility)': {Ride: 10, Style: 10, Leadership: 10, Persuasion: 15, History: {local: 10}, Appraisal: 10, Dance: 10, choices: [{Art: 5, Music: 5}]},
    'Remo (Middle Class / Lower Class)': {Athleticism: 10, Swim: 10, Jump: 10, Intimidate: 10, Notice: 10, Hide: 10, Theft: 10, Stealth: 10},
    'Remo (Bourgeois / Nobility)': {Ride: 10, Swim: 10, Persuasion: 10, Notice: 10, Composure: 10, Intimidate: 10, History: {local: 10}, Appraisal: 10},
    'Salazar (All Nomads)': {Athleticism: 15, Ride: 10, Notice: 10, Search: 10, Track: 15, Animals: 5, Hide: 5, Stealth: 10},
    'Shivat (Middle Class / Lower Class)': {Acrobatics: 10, Athleticism: 10, Swim: 10, Climb: 10, Style: 10, Notice: 10, Animals: 10, 'Herbal Lore': 10},
    'Shivat (Nobility / Bourgeoisie / Bureaucrat)': {Ride: 10, Style: 15, Persuasion: 20, Notice: 10, History: 10, Occult: 5, Dance: 5, choice: [{Art: 5}, {Music: 5}]},
    'The Dominion (Middle Class / Lower Class)': {Swim: 10, Persuasion: 10, Notice: 10, History: {Christian: 25}, Occult: {religion: 25}},
    'The Dominion (Nobility / Priest / High Nobility / Cardinal)': {Leadership: 10, Persuasion: 20, Notice: 10, History: {Christian: 20}, Occult: {religion: 30}},
    'Togarini (Middle Class / Lower Class)': {Athleticism: 10, Ride: 10, Climb: 10, Notice: 10, 'Sleight of Hand': 10, Composure: 10, Persuasion: 10, History: {local: 10}},
    'Togarini (Bourgeois)': {Ride: 10, Persuasion: 10, Style: 10, Composure: 10, History: {local: 10}, Appraisal: 20, Dance: 10},
    'Togarini (Nobility / High Nobility)': {Ride: 10, Style: 10, Composure: 10, Leadership: 10, Intimidate: 10, Persuasion: 10, History: {local: 10}, Dance: 10}
});
