/*global define: false */
/**
 * Data on the Metamagic spheres from Arcana Exxet.
 * @module metamagic
 */
define({
    A: {Name: 'Avatar', Cost: 20, Level: 9, Neighbors: ['AZR3', 'DMP7', 'UZ']},
    AZR1: {Name: 'Advanced Zeon Regeneration', Cost: 5, Neighbors: ['CM', 'DMP1', 'DMP2']},
    AZR2: {Name: 'Advanced Zeon Regeneration', Cost: 5, Level: 5, Neighbors: ['DMP4', 'DMP5']},
    AZR3: {Name: 'Advanced Zeon Regeneration', Cost: 5, Level: 8, Neighbors: ['A', 'CM']},
    BS: {Name: 'Bind Spells', Cost: 25, Level: 8, Neighbors: ['PR1', 'SIS']},
    CM: {Name: 'Combined Magic', Cost: 5, Level: 3, Neighbors: ['AZR1', 'AZR3', 'DMP2', 'DMP4', 'DMP6']},
    CS: {Name: 'Control Space', Cost: 10, Level: 6, Neighbors: ['DIS', 'TM']},
    DD: {Name: 'Double Damage', Cost: 20, Level: 10, Neighbors: ['OE3']},
    DE1: {Name: 'Defensive Expertise', Cost: 10, Neighbors: ['EA1', 'ES1', 'ID1', 'MA1', 'RP1']},
    DE2: {Name: 'Defensive Expertise', Cost: 10, Level: 5, Neighbors: ['ES2', 'FS3']},
    DE3: {Name: 'Defensive Expertise', Cost: 10, Level: 6, Neighbors: ['EA1', 'OE3']},
    DIS: {Name: 'Double Innate Spells', Cost: 20, Level: 7, Neighbors: ['CS', 'NM', 'SL2']},
    DMP1: {Name: 'Defined Magic Projection', Cost: 5, Neighbors: ['AZR1', 'DMP2', 'ENE1']},
    DMP2: {Name: 'Defined Magic Projection', Cost: 5, Neighbors: ['AZR1', 'CM', 'DMP1', 'ENE1', 'PE']},
    DMP3: {Name: 'Defined Magic Projection', Cost: 5, Level: 3, Neighbors: ['ENE2', 'SS6']},
    DMP4: {Name: 'Defined Magic Projection', Cost: 5, Level: 4, Neighbors: ['AZR2', 'CM']},
    DMP5: {Name: 'Defined Magic Projection', Cost: 5, Level: 5, Neighbors: ['AZR2', 'FS2']},
    DMP6: {Name: 'Defined Magic Projection', Cost: 5, Level: 6, Neighbors: ['CM', 'E', 'PE']},
    DMP7: {Name: 'Defined Magic Projection', Cost: 5, Level: 10, Neighbors: ['A', 'PE']},
    DS: {Name: 'Double Spell', Cost: 20, Level: 7, Neighbors: ['SS4', 'SIS']},
    E: {Name: 'Elevation', Cost: 5, Level: 6, Neighbors: ['DMP6']},
    EA1: {Name: 'Expanded Area', Cost: 10, Level: 3, Neighbors: ['DE1', 'DE3', 'ES1', 'OE1', 'RP2']},
    EA2: {Name: 'Expanded Area', Cost: 10, Level: 6, Neighbors: ['MA1', 'OE3']},
    EC: {Name: 'Energy Control', Cost: 10, Neighbors: ['ESD', 'FS1', 'LM1', 'SD', 'TM']},
    ENE1: {Name: 'Exploitation of Natural Energy', Cost: 5, Neighbors: ['DMP1', 'DMP2', 'PE']},
    ENE2: {Name: 'Exploitation of Natural Energy', Cost: 5, Level: 3, Neighbors: ['DMP3', 'PE']},
    ES1: {Name: 'Empowered Shields', Cost: 5, Neighbors: ['DE1', 'EA1', 'ID1']},
    ES2: {Name: 'Empowered Shields', Cost: 5, Level: 4, Neighbors: ['DE2', 'RP2']},
    ESD: {Name: 'Endure Supernatural Damage', Cost: 10, Level: 3, Neighbors: ['EC', 'FS1', 'HdM', 'LM2', 'SL2']},
    FM: {Name: 'Feel Magic', Cost: 5, Neighbors: ['FS3', 'TM']},
    FS1: {Name: 'Force Speed', Cost: 5, Neighbors: ['EC', 'ESD', 'LM1']},
    FS2: {Name: 'Force Speed', Cost: 5, Level: 2, Neighbors: ['DMP5', 'HdM']},
    FS3: {Name: 'Force Speed', Cost: 5, Level: 2, Neighbors: ['DE2', 'FM']},
    HdM: {Name: 'Hidden Magic', Cost: 5, Level: 2, Neighbors: ['ESD', 'FS2']},
    HgM: {Name: 'High Magic', Cost: 20, Level: 10, Neighbors: ['SIS']},
    ID1: {Name: 'Increased Destruction', Cost: 10, Neighbors: ['ES1', 'RP1']},
    ID2: {Name: 'Increased Destruction', Cost: 10, Level: 4, Neighbors: ['MA1', 'RP3']},
    IR1: {Name: 'Increased Range', Cost: 5, Neighbors: ['MC', 'PR1', 'SS1', 'SS2', 'SS4']},
    IR2: {Name: 'Increased Range', Cost: 5, Neighbors: ['SS3', 'SS4']},
    LM1: {Name: 'Life Magic', Cost: 5, Neighbors: ['EC', 'FS1', 'SD']},
    LM2: {Name: 'Life Magic', Cost: 5, Level: 3, Neighbors: ['ESD', 'SL1', 'TM']},
    MA1: {Name: 'Mystic Accuracy', Cost: 5, Level: 2, Neighbors: ['DE1', 'EA2', 'ID2', 'OE1', 'RP1']},
    MA2: {Name: 'Mystic Accuracy', Cost: 10, Level: 6, Neighbors: ['OE1']},
    MC: {Name: 'Mystic Concentration', Cost: 5, Neighbors: ['IR1', 'SS1', 'SS2']},
    MS: {Name: 'Maximize Spells', Cost: 10, Level: 5, Neighbors: ['PR1', 'SS4', 'SS7']},
    NM: {Name: 'Natural Maintenance', Cost: 20, Level: 10, Neighbors: ['DIS']},
    OE1: {Name: 'Offensive Expertise', Cost: 10, Level: 4, Neighbors: ['EA1', 'MA1', 'MA2']},
    OE2: {Name: 'Offensive Expertise', Cost: 10, Level: 5, Neighbors: ['RP3', 'SS3']},
    OE3: {Name: 'Offensive Expertise', Cost: 10, Level: 7, Neighbors: ['DD', 'DE3', 'EA2']},
    PE: {Name: 'Persistent Effects', Cost: 5, Level: 3, Neighbors: ['DMP2', 'DMP6', 'DMP7', 'ENE1', 'ENE2']},
    PR1: {Name: 'Pierce Resistances', Cost: 5, Level: 2, Neighbors: ['BS', 'IR1', 'MS', 'SS2']},
    PR2: {Name: 'Pierce Resistances', Cost: 5, Level: 4, Neighbors: ['SS5', 'SS6']},
    RP1: {Name: 'Remove Protection', Cost: 5, Neighbors: ['DE1', 'ID1', 'MA1']},
    RP2: {Name: 'Remove Protection', Cost: 5, Neighbors: ['EA1', 'ES2']},
    RP3: {Name: 'Remove Protection', Cost: 5, Neighbors: ['ID2', 'OE2']},
    SD: {Name: 'Secure Defense', Cost: 5, Neighbors: ['EC', 'LM1', 'TM']},
    SIS: {Name: 'Superior Innate Spell', Cost: 20, Level: 9, Neighbors: ['BS', 'DS', 'HgM']},
    SL1: {Name: 'Spiritual Loop', Cost: 15, Level: 6, Neighbors: ['LM2']},
    SL2: {Name: 'Spiritual Loop', Cost: 25, Level: 9, Neighbors: ['DIS', 'ESD']},
    SS1: {Name: 'Spell Specialist Level 30', Cost: 5, Neighbors: ['IR1', 'MC', 'SS4']},
    SS2: {Name: 'Spell Specialist Level 30', Cost: 5, Neighbors: ['IR1', 'MC', 'PR1']},
    SS3: {Name: 'Spell Specialist Level 50', Cost: 5, Level: 2, Neighbors: ['IR2', 'OE2']},
    SS4: {Name: 'Spell Specialist Level 60', Cost: 5, Level: 3, Neighbors: ['DS', 'IR1', 'IR2', 'MS', 'SS1']},
    SS5: {Name: 'Spell Specialist Level 60', Cost: 5, Level: 3, Neighbors: ['PR1', 'PR2']},
    SS6: {Name: 'Spell Specialist Level 70', Cost: 5, Level: 5, Neighbors: ['DMP3', 'PR2']},
    SS7: {Name: 'Spell Specialist Level 80', Cost: 5, Level: 8, Neighbors: ['MS']},
    TM: {Name: 'Transfer Magic', Cost: 10, Level: 3, Neighbors: ['CS', 'EC', 'FM', 'LM2', 'SD']},
    UZ: {Name: 'Unlimited Zeon', Cost: 20, Level: 10, Neighbors: ['A']}
});
