/*global define: false */
/**
 * Data on Combat Modules (weapons, fighting styles, etc.)
 * @module modules
 */
define({
    'Similar Weapon': {Primary: 'Combat', DP:10, WDP:5, Options: [], Option_Title: 'Select a Weapon'},
    'Mixed-Class Weapon': {Primary: 'Combat', DP:15, WDP:10, Options: [], Option_Title: 'Select a Weapon'},
    'Different Type / Unarmed': {Primary: 'Combat', DP:20, WDP:10, Options: [], Option_Title: 'Select a Weapon'},
    'Whole-Class Weapons': {Primary: 'Combat', DP:50, WDP:25, Options: ['Axe', 'Cord', 'Mace', 'Pole', 'Shield', 'Short Arm', 'Sword', 'Two-handed'], Option_Title: 'Select a Class of Weapons'},
    'Projectile Weapons': {Primary: 'Combat', DP:50, WDP:25},
    'Throwing': {Primary: 'Combat', DP:50, WDP:25},
    'Improvised Weapons': {Primary: 'Combat', DP:50, WDP:25},
    'Barbarian Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'War Axe, Battle Axe, Two-handed Sword, Bastard Sword, Heavy Battle Mace'},
    'Ninja Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'Katana, Tanto, Claws, Shuriken, Kusari-gama'},
    'Duel Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'Rapier, Foil, Parrying Dagger, Saber, Long Sword'},
    'Pirate Module': {Primary: 'Combat', DP:50, WDP:25, Notes: "Harpoon, Gladiator's Net, Hook, Saber, Handaxe"},
    'Nomad Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'Dagger, Chakram, Long Bow, Scimitar, Lance'},
    'Hunt Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'Javelin, Bow, Short Sword, Lance, Bolos'},
    'Knight Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'Long Sword, Cavalry Lance, Mace, Bastard Sword, Shield'},
    'Gladiator Module': {Primary: 'Combat', DP:50, WDP:25, Notes: "Short Sword, Gladiator's Net, Buckler, Trident, Whip"},
    'Assassin Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'Short Sword, Miniature Crossbow, Club, Blowgun, Stiletto'},
    'Soldier Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'Crossbow, Long Sword, Halberd, Lance, Shield'},
    'Indigenous Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'Javelin, Lance, Full Shield, Bow, Blowgun'},
    'Bandit Module': {Primary: 'Combat', DP:50, WDP:25, Notes: 'Dagger, Crossbow, Short Sword, Mace, Club'},
    'Batto jutsu / Iai jutsu': {Primary: 'Combat', DP:30, WDP:15},
    'Area Attack': {Primary: 'Combat', DP:40, WDP:20},
    'Precision Attack': {Primary: 'Combat', DP:50, WDP:25},
    'Disarming Attack': {Primary: 'Combat', DP:40, WDP:20},
    'Magic Projection as an Attack': {Primary: 'Supernatural', DP: 75, WDP:40},
    'Magic Projection as a Defense': {Primary: 'Supernatural', DP: 75, WDP:40},
    'Psychic Projection Module': {Primary: 'Psychic', DP:100, WDP:50},
    'Graceful Parry Module': {Primary: 'Combat', DP:30, WDP:15},
    'Armor Reduction Module': {Primary: 'Combat', DP:40, WDP:20},
    'Blind Fighting Module': {Primary: 'Combat', DP:40, WDP:20},
    'Running Shot Module': {Primary: 'Combat', DP:40, WDP:20},
    'Moving Target Module': {Primary: 'Combat', DP:50, WDP:25},
    'Multiple Target Module': {Primary: 'Combat', DP:40, WDP:20},
    'Defense Against Projectiles Module': {Primary: 'Combat', DP:40, WDP:20},
    'Additional Attacks Module': {Primary: 'Combat', DP:40, WDP:20},
    'Multiple Missiles': {Primary: 'Combat', DP:20, WDP:10},
    'Second Weapon: Defensive Style': {Primary: 'Combat', DP:30, WDP:15},
    'Increased Critical': {Primary: 'Combat', DP:20, WDP:10},
    'Unusual Attacks': {Primary: 'Combat', DP:20, WDP:10},
    'Unusual Traps': {Primary: 'Combat', DP:40, WDP:20},
    'Bodyguard': {Primary: 'Combat', DP:30, WDP:15},
    'Movement in Confined Spaces': {Primary: 'Combat', DP:30, WDP:15},
    'Dodging with Shield': {Primary: 'Combat', DP:30, WDP:15},
    'Firm Grip': {Primary: 'Combat', DP:10, WDP:5}
});
